# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399852d04c4f0c82a30ce92c738f3895045ad7053ee12e21d789845b951b113f7a49dd32c44c404e6f1e1bb042ec1c83aaff37acbac57d11823be12588f89e75

test:
  secret_key_base: 887ea5f7332d9df75e64901bfe0f877292e5a75f644a362cb1e646597757673bb15e3c8394e64e857aedaa5ffa00824c227ae9bef9a49628dde960c54a07d743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
